---
- name: config postgres cluster
  hosts: '{{ hosts | default("all") }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo

  vars:
    ansible_user: '{{ lookup("env","ANSIBLE_USER") }}'
    ansible_pass: '{{ lookup("env","ANSIBLE_PASS") }}'

  roles:
    - cluster
