---
- name: install postgresql server
  hosts: '{{ hosts | default("PGP2") }}'
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars:
    ansible_user: '{{ lookup("env","ANSIBLE_USER") }}'
    ansible_pass: '{{ lookup("env","ANSIBLE_PASS") }}'

  roles:
    - pgp2
