---
- name: install postgresql server
  hosts: '{{ hosts | default("PGPOOL") }}'
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars:
    ansible_user: '{{ lookup("env","ANSIBLE_USER") }}'
    ansible_pass: '{{ lookup("env","ANSIBLE_PASS") }}'
  
  pre_tasks:
    - name: gather master list
      set_fact:
        pgpool_list: '{{ groups["PGPOOL"] | map("extract", hostvars, ["inventory_hostname"]) | list }}'
        pgpool_hosts: '{{ groups["PGPOOL"] | map("extract", hostvars, ["inventory_hostname"]) | flatten }}'
      tags:
        - always

  roles:
    - pgpool
