---
- name: stop vm forcefully
  shell: ssh -o StrictHostKeyChecking=no root@{{ proxmox_host }} "qm stop {{ newid }} -skiplock true"
  ignore_errors: yes
  delegate_to: localhost
  tags:
    - stop

- name: stop vm
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_pass }}"
    api_host: "{{ proxmox_host }}"
    vmid: '{{ newid }}'
    state: stopped
  ignore_errors: yes
  delegate_to: localhost
  tags:
    - stop

- name: gather old mac addr
  shell: ssh -o StrictHostKeyChecking=no root@{{ proxmox_host }} 'qm config {{ newid }} | grep ^net0 | cut -d"=" -f2 | sed "s/,bridge//"'
  register: mac_addr
  delegate_to: localhost
  ignore_errors: yes
  notify:
    - unlease old mac for dhcp in dnsmasq
    - delete old mac for dhcp in dnsmasq
    - delete old hostname for dns in dnsmasq
  tags:
    - delete

- name: force all notified handlers to run about remove
  meta: flush_handlers

- name: remove vm
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_pass }}"
    api_host: "{{ proxmox_host }}"
    name: '{{ inventory_hostname }}'
    node: '{{ proxmox_node }}'
    state: absent
  ignore_errors: yes
  delegate_to: localhost
  notify:
    - unlease old mac for dhcp in dnsmasq
    - delete old mac for dhcp in dnsmasq
    - delete old hostname for dns in dnsmasq
  tags:
    - delete

- name: force all notified handlers to run about remove
  meta: flush_handlers

- name: restart dnsmasq
  systemd:
    state: restarted
    daemon_reload: yes
    name: dnsmasq
  delegate_to: '{{ bootstrap_host }}'
  run_once: true
  become: yes
  become_method: sudo
  tags:
    - delete

- name: clone vm
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_pass }}"
    api_host: "{{ proxmox_host }}"
    node: '{{ proxmox_node }}'
    clone: "{{ tmpl }}"
    vmid: '{{ vmid }}'
    newid: '{{ newid }}'
    name: '{{ inventory_hostname }}'
    storage: '{{ storage }}'
    timeout: '600'
    state: present
  delegate_to: localhost
  notify:
  tags:
    - create

- name: wait for clone vm
  wait_for:
    timeout: 10
  run_once: true
  delegate_to: localhost
  tags:
    - wait

- name: gather new mac addr
  shell: ssh -o StrictHostKeyChecking=no root@{{ proxmox_host }} 'qm config {{ newid }} | grep ^net0 | cut -d"=" -f2 | sed "s/,bridge//"'
  register: mac_addr
  delegate_to: localhost
  notify:
    - set mac for dhcp in dnsmasq
    - set hostname for dns in dnsmasq
  tags:
    - create

- name: force all notified handlers to run about remove
  meta: flush_handlers

- name: update vm
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_pass }}"
    api_host: "{{ proxmox_host }}"
    name: '{{ inventory_hostname }}'
    node: '{{ proxmox_node }}'
    cores: '{{ cores }}'
    memory: '{{ memory }}'
    update: yes
  delegate_to: localhost
  notify:
    - set mac for dhcp in dnsmasq
    - set hostname for dns in dnsmasq
  tags:
    - create

- name: change boot order and autostart
  shell: ssh root@{{ proxmox_host }} 'qm set {{ newid }} --onboot "0" --boot "order=scsi0;net0;net1"'
  delegate_to: localhost
  tags:
    - create

- name: force all notified handlers to run about remove
  meta: flush_handlers

- name: restart dnsmasq
  systemd:
    state: restarted
    daemon_reload: yes
    name: dnsmasq
  delegate_to: '{{ bootstrap_host }}'
  run_once: true
  become: yes
  become_method: sudo
  tags:
    - create

- name: wait for restart dnsmasq
  wait_for:
    timeout: 3
  run_once: true
  delegate_to: localhost
  tags:
    - wait

- name: start vm
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_pass }}"
    api_host: "{{ proxmox_host }}"
    vmid: '{{ newid }}'
    state: started
  delegate_to: localhost
  tags:
    - start
