---
- name: add the pgpool server in the firewalld
  firewalld:
    port: '{{ item.port }}'
    zone: '{{ item.zone }}'
    permanent: '{{ item.permanent }}'
    state: '{{ item.state }}'
  with_items:
  - { port: '9999/tcp', zone: 'public', permanent: yes, state: enabled }
  - { port: '9898/tcp', zone: 'public', permanent: yes, state: enabled }
  - { port: '9000/tcp', zone: 'public', permanent: yes, state: enabled }
  - { port: '9694/udp', zone: 'public', permanent: yes, state: enabled }
  tags:
  - pgp_firewall

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags:
  - pgp_firewall

- name: install the pgpool-II 4.2 and postgres repository 
  yum:
    name: '{{ item.name }}'
  with_items:
  - { name: 'https://www.pgpool.net/yum/rpms/{{ pgpool_version }}/redhat/rhel-8-x86_64/pgpool-II-release-4.2-1.noarch.rpm' }
  tags:
  - pgp_install

- name: install the pgpool-II 4.2
  yum:
    name:
    - sshpass
    - pgpool-II-pg{{ postgres_version }}
    - pgpool-II-pg{{ postgres_version }}-extensions
    enablerepo: ''
    state: present
  tags:
  - pgp_install

- name: delete old .ssh path
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  become_user: postgres
  with_items:
    - { path: "{{ postgres_user_home }}/.ssh", mode: "0700", state: absent }
    - { path: "{{ postgres_user_home }}/.ssh", mode: "0700", state: directory }

- name: generate ssh key for connecting without asking password
  shell: |
    ssh-keygen -q -t rsa -N '' -f {{ postgres_user_home }}/.ssh/id_rsa_pgpool <<< y
  become_user: postgres
  tags:
  - postgres_user

- name: copy ssh key
  shell: |
    sshpass -p{{ postgres_user_pass }} \
      ssh-copy-id -o StrictHostKeyChecking=no \
        -i {{ postgres_user_home }}/.ssh/id_rsa_pgpool \
        -f {{ postgres_user_name }}@{{ hostvars[item].inventory_hostname }}
  with_items:
  - '{{ groups["POSTGRES"] }}'
  become_user: postgres
  tags:
  - postgres_user

- name: enable service pgpool
  systemd:
    name: pgpool
    enabled: yes
    state: stopped
  tags:
  - pgp_service

- name: change directory permission for pgpool
  file:
    path: '/etc/pgpool-II'
    owner: postgres
    group: postgres
    state: 'directory'
  tags:
  - pgp_config
  - pgp_dir

- name: copy base configuration file
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
    mode: '0644'
    remote_src: yes
  with_items:
    - { src: '/etc/pgpool-II/pool_hba.conf.sample', dest: '/etc/pgpool-II/pool_hba.conf' }
    - { src: '/etc/pgpool-II/pcp.conf.sample', dest: '/etc/pgpool-II/pcp.conf' }
  tags:
    - pgp_config

- name: create pgpool_node_id
  shell: |
    echo {{ inventory_hostname[-1:] | int - 1 }} > /etc/pgpool-II/pgpool_node_id
  tags:
  - pgp_config
  - pgp_node_id

- name: change pgpool config
  template:
    src: pgpool/pgpool.conf.j2
    dest: /etc/pgpool-II/pgpool.conf
    owner: postgres
    group: postgres
    mode: 0600
  tags:
  - pgp_config

- name: change maximum connection in pgpool config
  replace:
    path: "{{ itme.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  become_user: postgres
  with_items:
    - {
        path: "/etc/pgpool-II/pgpool.conf",
        regexp: "^num_init_children = 32",
        replace: "num_init_children = 512",
      }
    - {
        path: "/etc/pgpool-II/pgpool.conf",
        regexp: "^max_pool = 4",
        replace: "max_pool = 2",
      }
  tags:
    - pgp_config

- name: change backend connection settings in pgpool config file
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    insertafter: '^# - Backend Connection Settings -'
    line: |
      backend_hostname{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = '{{ hostvars[item].inventory_hostname }}'
      backend_port{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = 5432
      backend_weight{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = 1
      backend_data_directory{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = '{{ postgres_pgdata }}'
      backend_flag{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = 'ALLOW_TO_FAILOVER'
      backend_application_name{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = '{{ hostvars[item].inventory_hostname }}'
  with_items:
  - '{{ groups["PGPOOL"] }}'
  tags:
  - pgp_config

- name: copy failover shell file
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
    mode: 0750
    remote_src: yes
  with_items:
  - { src: '/etc/pgpool-II/failover.sh.sample', dest: '/etc/pgpool-II/failover.sh' }
  - { src: '/etc/pgpool-II/follow_primary.sh.sample', dest: '/etc/pgpool-II/follow_primary.sh' }
  tags:
  - pgp_config

- name: change env in failover shell file
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
  # - { path: '/etc/pgpool-II/failover.sh', regexp: '^PGHOME=/usr/pgsql-13', replace: 'PGHOME=/usr/pgsql-{{ postgres_version }}' }
  # - { path: '/etc/pgpool-II/follow_primary.sh', regexp: '^PGHOME=/usr/pgsql-13', replace: 'PGHOME=/usr/pgsql-{{ postgres_version }}' }
  - { path: '/etc/pgpool-II/follow_primary.sh', regexp: '^ARCHIVEDIR=/var/lib/pgsql/archivedir', replace: 'ARCHIVEDIR={{ postgres_pgarchive }}'}
  - { path: '/etc/pgpool-II/follow_primary.sh', regexp: '^REPLUSER=repl', replace: 'REPLUSER={{ postgres_replica_name }}' }
  - { path: '/etc/pgpool-II/follow_primary.sh', regexp: '^PCP_USER=pgpool', replace: 'PCP_USER={{ postgres_pgpool_name }}' }
  tags:
  - pgp_config

- name: create the encrypted password file
  file:
    path: '{{ item.path }}'
    owner: postgres
    group: postgres
    mode: '{{ item.mode }}'
    state: '{{ item.state }}'
  with_items:
    - { path: '{{ postgres_user_home }}/.pcppass', mode: '0600', state: absent }
    - { path: '{{ postgres_user_home }}/.pcppass', mode: '0600', state: touch }

- name: create the encrypted password entry for watchdog
  lineinfile:
    line: '{{ item.line }}'
    insertafter: 'EOF'
    path: ~postgres/.pcppass
    create: yes
  become_user: postgres
  with_items:
  - { line: 'localhost:9898:{{ postgres_pgpool_name }}:{{ postgres_pgpool_pass }}' }
  - { line: '{{ pgpool_vip }}:9898:{{ postgres_pgpool_name }}:{{ postgres_pgpool_pass }}' }
  tags:
  - pgp_config

- name: create the encrypted password for pgpool
  shell: |
    echo "pgpool:`pg_md5 {{ postgres_user_pass }}`" >> /etc/pgpool-II/pcp.conf

- name: copy online recovery shell file
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
    mode: 0755
    remote_src: yes
  with_items:
    - { src: '/etc/pgpool-II/recovery_1st_stage.sample', dest: '{{ postgres_pgdata }}/recovery_1st_stage' }
    - { src: '/etc/pgpool-II/recovery_2nd_stage.sample', dest: '{{ postgres_pgdata }}/recovery_2nd_stage' }
    - { src: '/etc/pgpool-II/pgpool_remote_start.sample', dest: '{{ postgres_pgdata }}/pgpool_remote_start' }
  tags:
  - pgp_config

- name: change envs in online recovery shell file
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { path: '{{ postgres_pgdata }}/recovery_1st_stage', regexp: '^PGHOME=/usr/pgsql-13', replace: 'PGHOME=/usr/pgsql-{{ postgres_version }}' }
    - { path: '{{ postgres_pgdata }}/recovery_1st_stage', regexp: '^ARCHIVEDIR=/var/lib/pgsql/archivedir', replace: 'ARCHIVEDIR={{ postgres_pgarchive }}' }
    - { path: '{{ postgres_pgdata }}/recovery_1st_stage', regexp: '^REPLUSER=repl', replace: 'REPLUSER={{ postgres_replica_name }}' }
    - { path: '{{ postgres_pgdata }}/recovery_1st_stage', regexp: "passfile='/var/lib/pgsql/.pgpass'", replace: "passfile='{{ postgres_user_home }}/.pgpass'" }
    - { path: '{{ postgres_pgdata }}/recovery_2st_stage', regexp: '^PGHOME=/usr/pgsql-13', replace: 'PGHOME=/usr/pgsql-{{ postgres_version }}' }
    - { path: '{{ postgres_pgdata }}/recovery_2st_stage', regexp: '^ARCHIVEDIR=/var/lib/pgsql/archivedir', replace: 'ARCHIVEDIR={{ postgres_pgarchive }}' }
    - { path: '{{ postgres_pgdata }}/recovery_2st_stage', regexp: '^REPLUSER=repl', replace: 'REPLUSER={{ postgres_replica_name }}' }
  tags:
  - pgp_config

- name: recreate recovery extension for online recovery
  shell: |
    psql template1 -c "{{ item.type }} EXTENSION pgpool_recovery"
  become_user: postgres
  with_items:
    - { type: 'DROP' }
    - { type: 'CREATE' }
  when: inventory_hostname == groups['POSTGRES'][0]
  ignore_errors: yes
  tags:
  - pgp_config

- name: specify all pgpool nodes information for configuring watchdog
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    insertafter: '^# - Watchdog communication Settings -'
    line: |
      hostname{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = '{{ hostvars[item].inventory_hostname }}'
      wd_port{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = 9000
      pgpool_port{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = 9999
  with_items:
  - '{{ groups["PGPOOL"] }}'
  tags:
  - pgp_watchdog

- name: specify all Pgpool-II nodes information for sending and receiving heartbeat signal
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    insertafter: '^# -- heartbeat mode --'
    line: |
      heartbeat_hostname{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = '{{ hostvars[item].inventory_hostname }}'
      heartbeat_port{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = 9694
      heartbeat_device{{ hostvars[item].inventory_hostname[-1:] | int - 1 }} = ''
  become_user: postgres
  with_items:
  - '{{ groups["PGPOOL"] }}'
  tags:
  - pgp_watchdog

- name: copy sample script for escalation
  shell: |
    cp -p /etc/pgpool-II/escalation.sh{.sample,}
    chown postgres:postgres /etc/pgpool-II/escalation.sh
  tags:
  - pgp_watchdog

- name: change envs in escalation script
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
  - { path: '/etc/pgpool-II/escalation.sh', regexp: 'server1 server2 server3', replace: '{{ pgpool_list | join(" ") }}' }
  - { path: '/etc/pgpool-II/escalation.sh', regexp: '^VIP=192.168.137.150', replace: 'VIP={{ pgpool_vip }}' }
  - { path: '/etc/pgpool-II/escalation.sh', regexp: '^DEVICE=enp0s8', replace: 'DEVICE=eth0' }
  tags:
  - pgp_watchdog

- name: create the log directory on all servers
  file:
    path: '{{ item.dir }}'
    owner: postgres
    group: postgres
    mode: '{{ item.mode }}'
    state: directory
  with_items:
  - { dir: '/var/log/pgpool', mode: '0755' }
  tags:
  - pgp_log

- name: change envs for string pgpool
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
  - { path: '/etc/sysconfig/pgpool', regexp: 'OPTS=" -n"', replace: 'OPTS=" -D -n"' }
  tags:
  - pgp_service_start

- name: start pgpool service
  systemd:
    name: pgpool
    daemon_reload: yes
    state: started
  tags:
  - pgp_service_start

- name: wait for starting pgpool service
  wait_for:
    host: "{{ pgpool_vip }}"
    port: 9999
    delay: 10
    state: started
  when: inventory_hostname = groups['POSTGRES'][0]
  tags:
    - pgp_service_start

- name: setup postgres standby server first
  shell: |
    /usr/pgsql-{{ postgres_version }}/bin/pg_ctl -D {{ postgres_pgdata }} -m immediate stop
    sleep 10
    pcp_recovery_node -h {{ pgpool_vip }} -p 9898 -U pgpool -n 1 -w
  become_user: postgres
  when: inventory_hostname == groups['POSTGRES'][1]
  tags:
    - pgp_standby

- name: wait for starting standby server first
  wait_for:
    host: "{{ hostvars[inventory_hostname].ip }}"
    port: 5432
    delay: 3
    state: started
  when: inventory_hostname = groups['POSTGRES'][1]
  tags:
    - pgp_service_start

- name: setup postgres standby server second
  shell: |
    /usr/pgsql-{{ postgres_version }}/bin/pg_ctl -D {{ postgres_pgdata }} -m immediate stop
    sleep 10
    pcp_recovery_node -h {{ pgpool_vip }} -p 9898 -U pgpool -n 2 -w
  become_user: postgres
  when: inventory_hostname == groups['POSTGRES'][2]
  tags:
    - pgp_standby

- name: wait for starting standby server second
  wait_for:
    host: "{{ hostvars[inventory_hostname].ip }}"
    port: 5432
    delay: 3
    state: started
  when: inventory_hostname = groups['POSTGRES'][2]
  tags:
    - pgp_service_start
