---
- name: wait for connection to be installed os
  wait_for_connection:
    sleep: 3
    connect_timeout: 1
    timeout: 1800
  tags:
    - wait

- name: sleep for cluster to be ready
  wait_for:
    port: 22
    state: started
    timeout: 600
  tags:
    - wait

- name: set hostname
  shell: |
    hostnamectl set-hostname '{{ inventory_hostname }}'
  tags:
  - hostname

- name: Disable swap for current session
  shell: |
    swapoff -a
    rm -f /swap.img
  tags:
  - swap

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
  tags:
  - swap

- name: copy dns file
  template:
    src: dns/resolv.conf
    dest: /etc/resolv.conf
  tags:
  - dns

- name: create a new data partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
  when: inventory_hostname in groups['POSTGRES']
  tags:
  - fs_xfs

- name: create a xfs filesystem on /dev/sdb1
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
    force: yes
  when: inventory_hostname in groups['POSTGRES']
  tags:
  - fs_xfs

- name: mount and bind a volume
  mount:
    path: /data1
    src: /dev/sdb1
    state: mounted
    fstype: xfs
  when: inventory_hostname in groups['POSTGRES']
  tags:
  - fs_xfs

- name: disable ipv6 kernel parameter
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - {
        path: "/etc/sysctl.d/99-disable-ipv6.conf",
        line: "net.ipv6.conf.all.disable_ipv6 = 1",
      }
    - {
        path: "/etc/sysctl.d/99-disable-ipv6.conf",
        line: "net.ipv6.conf.default.disable_ipv6 = 1",
      }
  tags:
    - kernel

- name: set kernel parameter for postgres
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - {
        path: "/etc/sysctl.d/01-postgres.conf",
        line: "kernel.shmall = 1230591",
      }
    - {
        path: "/etc/sysctl.d/01-postgres.conf",
        line: "kernel.shmmax = 5040500736",
      }
    - {
        path: "/etc/sysctl.d/01-postgres.conf",
        line: "fs.file-max = 65536",
      }
    - {
        path: "/etc/sysctl.d/01-postgres.conf",
        line: "vm.swappiness = 0",
      }
  tags:
    - kernel

- name: set limits for postgres
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - {
        path: "/etc/security/limits.d/postgres.conf",
        line: "postgres soft nofile 65535",
      }
    - {
        path: "/etc/security/limits.d/postgres.conf",
        line: "postgres hard nofile 65535",
      }
  tags:
    - limit

- name: reboot
  reboot:
    reboot_timeout: 60
  tags:
    - reboot