---
- name: install the postgres repository rpm from a remote repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  tags:
  - postgres_yum

- name: install postgres server and client
  yum:
    name:
    - vim
    - sshpass
    - postgresql{{ postgres_version }}-contrib
    - postgresql{{ postgres_version }}-server
    state: present
  tags:
  - postgres_install

- name: add the postgresql server in the firewalld
  firewalld:
    service: '{{ item.name }}'
    permanent: '{{ item.permanent }}'
    state: '{{ item.state }}'
  with_items:
  - { name: 'postgresql', permanent: yes, state: enabled }
  tags:
  - postgres_firewalld

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags:
  - postgres_firewalld

- name: stop postgresql server
  systemd:
    name: postgresql-{{ postgres_version }}
    daemon_reload: yes
    state: stopped
  ignore_errors: yes
  tags:
  - postgres_stop

- name: delete old postgresql data
  file:
    path: '{{ item.dir }}'
    state: absent
  with_items:
  - { dir: '/var/lib/pgsql/{{ postgres_version }}' }
  - { dir: '{{ postgres_user_home }} '}
  - { dir: '{{ postgres_pgdata }}' }
  - { dir: '{{ postgres_pgbackup }}' }
  - { dir: '{{ postgres_pgarchivelog }}' }
  tags:
  - postgres_dir

- name: create data directory
  file:
    path: '{{ item.dir }}'
    owner: postgres
    group: postgres
    mode: 0755
    state: directory
  with_items:
  - { dir: '/var/lib/pgsql/{{ postgres_version }}' }
  - { dir: '{{ postgres_user_home }} '}
  - { dir: '{{ postgres_pgdata }}' }
  - { dir: '{{ postgres_pgbackup }}' }
  - { dir: '{{ postgres_pgarchivelog }}' }
  tags:
  - postgres_dir

- name: initialize database
  shell: |
    /usr/pgsql-{{ postgres_version }}/bin/postgresql-{{ postgres_version }}-setup initdb
  environment:
    PGSETUP_INITDB_OPTIONS: "-D {{ postgres_pgdata }}"
  register: result
  failed_when: result.rc > 1
  tags:
  - postgres_init

- name: change pgdata to new location in service file
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
  - { path: '/usr/lib/systemd/system/postgresql-{{ postgres_version }}.service', regexp: '^Environment=PGDATA=/var/lib/pgsql/{{ postgres_version }}/data/', replace: 'Environment=PGDATA={{ postgres_pgdata }}/' }
  - { path: '{{ postgres_pgdata }}/postgresql.conf', regexp: "^#listen_addresses = 'localhost'", replace: "listen_addresses = '*'" }
  tags:
  - postgres_service

- name: change essential parameter in postgresql.conf for master server
  replace:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  become_user: postgres
  with_items:
  - { path: '{{ postgres_pgdata }}/postgresql.conf', regexp: '^#wal_level = replica', replace: 'wal_level = replica' }
  - { path: '{{ postgres_pgdata }}/postgresql.conf', regexp: '^#max_wal_senders = 10', replace: 'max_wal_senders = 10' }
  - { path: '{{ postgres_pgdata }}/postgresql.conf', regexp: '^#wal_keep_segments = 0', replace: 'wal_keep_segments = 10' }
  - { path: '{{ postgres_pgdata }}/postgresql.conf', regexp: '^#archive_mode = off', replace: 'archive_mode = on' }
  - { path: '{{ postgres_pgdata }}/postgresql.conf', regexp: "^#archive_command = ''", replace: "archive_command = 'cp %p {{ postgres_pgarchivelog }}/%f'" }
  when: inventory_hostname == groups['POSTGRES'][0]
  tags:
  - postgres_service

- name: change postgres's home directory
  user:
    name: postgres
    home: '{{ postgres_user_home }}'
    password: '{{ postgres_user_pass | password_hash("sha512") }}'
    create_home: no
    move_home: no
    state: present
  tags:
  - postgres_user

# - name: generate ssh key for connecting without asking password
#   shell: |
#     ssh-keygen -q -t rsa -N '' -f {{ postgres_user_home }}/.ssh/id_rsa <<< y
#   become_user: postgres
#   tags:
#   - postgres_user

# - name: copy ssh key
#   shell: |
#     sshpass -p{{ postgres_user_pass }} ssh-copy-id -o StrictHostKeyChecking=no postgres@postgres1
#     sshpass -p{{ postgres_user_pass }} ssh-copy-id -o StrictHostKeyChecking=no postgres@postgres2
#   become_user: postgres
#   tags:
#   - postgres_user

- name: start postgresql server
  systemd:
    name: postgresql-{{ postgres_version }}
    daemon_reload: yes
    state: started
  tags:
  - postgres_start

- name: change listen address dynamically to all
  shell: |
    psql -c "ALTER SYSTEM SET listen_addresses TO '*';"
  become_user: postgres
  tags:
  - postgres_config

- name: change postgres user password
  shell: |
    psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_user_pass }}';"
  become_user: postgres
  when: inventory_hostname == groups['POSTGRES'][0]
  tags:
  - postgres_config

- name: create users for replication and pgp2
  shell: |
    psql -c "DROP ROLE IF EXISTS {{ postgres_replica_user }}; CREATE ROLE {{ postgres_replica_user }} WITH REPLICATION LOGIN PASSWORD '{{ postgres_replica_pass }}';"
    psql -c "DROP ROLE IF EXISTS {{ postgres_pgp2_user }}; CREATE ROLE {{ postgres_pgp2_user }} WITH LOGIN PASSWORD '{{ postgres_pgp2_pass }}';"
    psql -c "GRANT pg_monitor TO {{ postgres_pgp2_user }};"
  become_user: postgres
  when: inventory_hostname == groups['POSTGRES'][0]
  tags:
  - postgres_replica

- name: add connection info to pg_hba for replication
  lineinfile:
    path: '{{ postgres_pgdata }}/pg_hba.conf'
    line: 'host    replication    {{ postgres_replica_user }}    {{ hostvars[item].ip }}/32    trust'
    state: present
  become_user: postgres
  with_items:
  - '{{ groups["POSTGRES"] }}'
  tags:
  - postgres_replica

- name: add connection info to pg_hba for pgp2
  lineinfile:
    path: '{{ postgres_pgdata }}/pg_hba.conf'
    line: 'host    replication    {{ postgres_pgp2_user }}    {{ hostvars[item].ip }}/32    trust'
    state: present
  become_user: postgres
  with_items:
  - '{{ groups["PGP2"] }}'
  tags:
  - postgres_pgp2

- name: reload postgres config
  shell: |
    psql -c "SELECT pg_reload_conf();"
  become_user: postgres
  tags:
  - postgres_config
  - postgres_replica
  - postgres_pgp2
  - postgres_master

- name: stop postgresql standby server
  systemd:
    name: postgresql-{{ postgres_version }}
    daemon_reload: yes
    state: stopped
  ignore_errors: yes
  when: inventory_hostname != groups['POSTGRES'][0]
  tags:
  - postgres_standby

- name: delete old postgresql data on standby
  file:
    path: '{{ item.dir }}'
    state: absent
  with_items:
  - { dir: '{{ postgres_pgdata }}' }
  - { dir: '{{ postgres_pgbackup }}' }
  - { dir: '{{ postgres_pgarchivelog }}' }
  when: inventory_hostname != groups['POSTGRES'][0]
  tags:
  - postgres_standby

- name: create data directory on standby
  file:
    path: '{{ item.dir }}'
    owner: postgres
    group: postgres
    mode: 0755
    state: directory
  with_items:
  - { dir: '{{ postgres_pgbackup }}' }
  - { dir: '{{ postgres_pgarchivelog }}' }
  when: inventory_hostname != groups['POSTGRES'][0]
  tags:
  - postgres_standby

- name: base backup of the master server from the standby server
  shell: |
    pg_basebackup -h {{ hostvars[groups["POSTGRES"][0]].ip }} -D {{ postgres_pgdata }} -U {{ postgres_replica_user }} -P -v -R -X stream -C -S {{ inventory_hostname }}
  become_user: postgres
  when: inventory_hostname != groups['POSTGRES'][0]
  tags:
  - postgres_standby

- name: start postgresql server on standby
  systemd:
    name: postgresql-{{ postgres_version }}
    daemon_reload: yes
    state: started
  when: inventory_hostname != groups['POSTGRES'][0]
  tags:
  - postgres_standby

- name: create .pgpass file
  file:
    path: '{{ postgres_user_home }}/.pgpass'
    owner: postgres
    group: postgres
    mode: '0600'
    state: touch
  tags:
  - postgres_pgpass

- name: config .pgpass file to allow user without password
  lineinfile:
    path: '{{ postgres_user_home }}/.pgpass'
    line: '{{ item.line }}'
    state: present
  become_user: postgres
  with_items:
  - { line: '{{ inventory_hostname }}:5432:replication:{{ postgres_replica_user }}:{{ postgres_replica_pass }}' }
  - { line: '{{ inventory_hostname }}:5432:postgres:postgres:{{ postgres_user_pass }}' }
  tags:
  - postgres_pgpass
